In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from glob import glob

from allensdk.brain_observatory.behavior.behavior_session import BehaviorSession
from allensdk.brain_observatory.behavior.behavior_ophys_experiment import BehaviorOphysExperiment

Below are some example data access code for BehaviorSession and OphysExperiment data. For the session/experiment objects themselves, I'm looking for any feedback regarding missing data or incorrectly formated data. For the pandas tables the question regards any incorrect typing or formating of the data. If you find issues beyond some that are already know (for instance `age_in_days` being float and not int, mouseid being typed `object`, or the ophys_experiment NWB I produced below missing a project code.) please create an issue on the AllenSDK. Thanks!

The code below requires the rc/2.15.0 branch of the AllenSDK. To install from the command line (assuming you have `git` installed) use:

`git clone https://github.com/AllenInstitute/AllenSDK`

`cd your_newly_cloned_AllenSDK_directory`

`git checkout rc/2.15.0`

`pip install -e .`

In [2]:
base_path = Path('/allen/aibs/informatics/chris.morrison/vbo_nbw_test')

Behavior only
----------------

In [3]:
behavior_sessions = pd.read_csv(base_path / 'behavior_session_table.csv')
behavior_sessions

,behavior_session_id,equipment_name,full_genotype,mouse_id,reporter_line,driver_line,sex,age_in_days,session_type,cre_line,...,miss_trial_count,false_alarm_trial_count,correct_reject_trial_count,engaged_trial_count,ophys_session_id,imaging_plane_group_count,ophys_experiment_id,ophys_container_id,date_of_acquisition,project_code
0,870987812,BEH.D-Box1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,80.0,TRAINING_0_gratings_autorewards_15min,Sst-IRES-Cre,...,0,0,0,70,NaN,NaN,NaN,NaN,2019-05-17 14:46:33.550,VisualBehaviorMultiscope
1,872953842,BEH.D-Box1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,84.0,TRAINING_1_gratings,Sst-IRES-Cre,...,275,4,45,27,NaN,NaN,NaN,NaN,2019-05-21 13:22:20.613,VisualBehaviorMultiscope
2,873774125,BEH.D-Box1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,85.0,TRAINING_1_gratings,Sst-IRES-Cre,...,300,3,38,0,NaN,NaN,NaN,NaN,2019-05-22 13:19:52.005,VisualBehaviorMultiscope
3,874790261,BEH.D-Box1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,86.0,TRAINING_1_gratings,Sst-IRES-Cre,...,312,0,42,0,NaN,NaN,NaN,NaN,2019-05-23 13:40:31.405,VisualBehaviorMultiscope
4,875207834,BEH.D-Box1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,87.0,TRAINING_1_gratings,Sst-IRES-Cre,...,300,3,41,5,NaN,NaN,NaN,NaN,2019-05-24 11:06:39.332,VisualBehaviorMultiscope
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4782,993537991,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,128.0,OPHYS_2_images_B_passive,Vip-IRES-Cre,...,357,0,52,0,993512923.0,NaN,[993590480],[991913246],2019-12-10 12:25:49.549,VisualBehaviorTask1B
4783,993691759,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,129.0,OPHYS_4_images_A,Vip-IRES-Cre,...,114,6,20,314,993668836.0,NaN,[993862120],[991913246],2019-12-11 08:57:44.877,VisualBehaviorTask1B
4784,993959724,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,130.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,353,0,49,0,993948045.0,NaN,[994053909],[991913246],2019-12-12 09:29:20.785,VisualBehaviorTask1B
4785,994710581,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,134.0,OPHYS_6_images_A,Vip-IRES-Cre,...,35,5,10,87,994689422.0,NaN,[994791582],[991913246],2019-12-16 09:27:10.443,VisualBehaviorTask1B
4786,994882261,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,135.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,354,0,50,0,994868382.0,NaN,[994956406],[991913246],2019-12-17 09:39:25.881,VisualBehaviorTask1B

In [4]:
# Example behavior session NWB. There are several others to test in the same directory.
behavior_session = BehaviorSession.from_nwb_path(base_path / 'behavior_sessions/893560763.nwb')

In [5]:
behavior_session.stimulus_presentations

,duration,end_frame,flashes_since_change,image_index,image_name,is_change,is_image_novel,movie_frame_index,omitted,repeat,start_frame,start_time,stimulus_block,stimulus_name,end_time
stimulus_presentations_id,,,,,,,,,,,,,,,
0,0.250219,18000,0.0,0.0,im065,False,False,NaN,False,NaN,17985,300.021065,0,Natural_Images_Lum_Matched_set_training_2017,300.271285
1,0.250237,18045,1.0,0.0,im065,False,False,NaN,False,NaN,18030,300.771696,0,Natural_Images_Lum_Matched_set_training_2017,301.021932
2,0.250198,18090,2.0,0.0,im065,False,False,NaN,False,NaN,18075,301.522332,0,Natural_Images_Lum_Matched_set_training_2017,301.772530
3,0.250206,18135,3.0,0.0,im065,False,False,NaN,False,NaN,18120,302.272965,0,Natural_Images_Lum_Matched_set_training_2017,302.523171
4,0.250191,18180,4.0,0.0,im065,False,False,NaN,False,NaN,18165,303.023618,0,Natural_Images_Lum_Matched_set_training_2017,303.273809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13782,0.033366,269823,9094.0,NaN,NaN,False,<NA>,895.0,<NA>,9.0,269822,4500.894073,2,natural_movie_one,4500.927438
13783,0.033352,269825,9095.0,NaN,NaN,False,<NA>,896.0,<NA>,9.0,269824,4500.927438,2,natural_movie_one,4500.960790
13784,0.033365,269827,9096.0,NaN,NaN,False,<NA>,897.0,<NA>,9.0,269826,4500.960790,2,natural_movie_one,4500.994155
13785,0.033369,269829,9097.0,NaN,NaN,False,<NA>,898.0,<NA>,9.0,269828,4500.994155,2,natural_movie_one,4501.027524
13786,0.016674,269831,9098.0,NaN,NaN,False,<NA>,899.0,<NA>,9.0,269830,4501.027524,2,natural_movie_one,4501.044198

In [6]:
behavior_session.metadata

{'equipment_name': 'BEH.D-Box3',
 'sex': 'F',
 'age_in_days': 233,
 'stimulus_frame_rate': 60.0,
 'session_type': 'TRAINING_5_images_A_handoff_ready',
 'date_of_acquisition': datetime.datetime(2019, 6, 24, 13, 10, 41, 640000, tzinfo=tzutc()),
 'reporter_line': 'Ai148(TIT2L-GC6f-ICL-tTA2)',
 'cre_line': 'Sst-IRES-Cre',
 'behavior_session_uuid': UUID('54e58e01-0dc4-44fb-81f5-7cda93591eca'),
 'driver_line': ['Sst-IRES-Cre'],
 'mouse_id': 457841,
 'project_code': 'VisualBehaviorMultiscope',
 'full_genotype': 'Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt',
 'behavior_session_id': 893560763}

Ophys Experiment
-----------

In [7]:
ophys_experiments = pd.read_csv(base_path / 'ophys_experiment_table.csv')
ophys_experiments

,ophys_experiment_id,equipment_name,full_genotype,mouse_id,reporter_line,driver_line,sex,age_in_days,session_type,cre_line,...,experiment_workflow_state,isi_experiment_id,imaging_depth,targeted_structure,published_at,date_of_acquisition,project_code,experience_level,passive,image_set
0,951980471,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,passed,848974280,150,VISp,2021-03-25,2019-09-20 09:59:38.837,VisualBehaviorMultiscope,Familiar,False,A
1,951980473,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,passed,848974280,225,VISp,2021-03-25,2019-09-20 09:59:38.837,VisualBehaviorMultiscope,Familiar,False,A
2,951980475,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,passed,848974280,75,VISp,2021-03-25,2019-09-20 09:59:38.837,VisualBehaviorMultiscope,Familiar,False,A
3,951980479,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,passed,848974280,150,VISl,2021-03-25,2019-09-20 09:59:38.837,VisualBehaviorMultiscope,Familiar,False,A
4,951980481,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,passed,848974280,225,VISl,2021-03-25,2019-09-20 09:59:38.837,VisualBehaviorMultiscope,Familiar,False,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936,993590480,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,128.0,OPHYS_2_images_B_passive,Vip-IRES-Cre,...,passed,967103425,175,VISp,2021-03-25,2019-12-10 12:25:49.549,VisualBehaviorTask1B,Familiar,True,B
1937,993862120,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,129.0,OPHYS_4_images_A,Vip-IRES-Cre,...,passed,967103425,175,VISp,2021-03-25,2019-12-11 08:57:44.877,VisualBehaviorTask1B,Novel 1,False,A
1938,994053909,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,130.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,passed,967103425,175,VISp,2021-03-25,2019-12-12 09:29:20.785,VisualBehaviorTask1B,Novel >1,True,A
1939,994791582,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,134.0,OPHYS_6_images_A,Vip-IRES-Cre,...,passed,967103425,175,VISp,2021-03-25,2019-12-16 09:27:10.443,VisualBehaviorTask1B,Novel >1,False,A
1940,994956406,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,135.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,passed,967103425,175,VISp,2021-03-25,2019-12-17 09:39:25.881,VisualBehaviorTask1B,Novel >1,True,A

In [8]:
# Example ophys experiment NWB. There are several others to test in the same directory.
ophys_experiment = BehaviorOphysExperiment.from_nwb_path(base_path / 'ophys_experiments/795952471.nwb')

/allen/aibs/informatics/chris.morrison/miniconda/envs/allensdk_jupyter/lib/python3.8/site-packages/pynwb/base.py:193: UserWarning: RoiResponseSeries 'RMSE': Length of data does not match length of timestamps. Your data may be transposed. Time should be on the 0th dimension
  warn("%s '%s': Length of data does not match length of timestamps. Your data may be transposed. "
/allen/aibs/informatics/chris.morrison/miniconda/envs/allensdk_jupyter/lib/python3.8/site-packages/pynwb/base.py:193: UserWarning: RoiResponseSeries 'r': Length of data does not match length of timestamps. Your data may be transposed. Time should be on the 0th dimension
  warn("%s '%s': Length of data does not match length of timestamps. Your data may be transposed. "

In [9]:
ophys_experiment.stimulus_presentations

,duration,end_frame,flashes_since_change,image_index,image_name,is_change,is_image_novel,movie_frame_index,omitted,repeat,start_frame,start_time,stimulus_block,stimulus_name,end_time
stimulus_presentations_id,,,,,,,,,,,,,,,
0,0.25010,17999,0.0,0.0,im000,False,False,NaN,False,NaN,17984,308.475208,0,Natural_Images_Lum_Matched_set_ophys_6_2017,308.725308
1,0.25027,18044,1.0,0.0,im000,False,False,NaN,False,NaN,18029,309.225748,0,Natural_Images_Lum_Matched_set_ophys_6_2017,309.476018
2,0.25030,18089,2.0,0.0,im000,False,False,NaN,False,NaN,18074,309.976348,0,Natural_Images_Lum_Matched_set_ophys_6_2017,310.226648
3,0.25014,18134,3.0,0.0,im000,False,False,NaN,False,NaN,18119,310.727038,0,Natural_Images_Lum_Matched_set_ophys_6_2017,310.977178
4,0.25018,18179,4.0,0.0,im000,False,False,NaN,False,NaN,18164,311.477668,0,Natural_Images_Lum_Matched_set_ophys_6_2017,311.727848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13808,0.03337,270497,9002.0,NaN,NaN,False,<NA>,895.0,<NA>,9.0,270496,4520.611958,2,natural_movie_one,4520.645328
13809,0.03335,270499,9003.0,NaN,NaN,False,<NA>,896.0,<NA>,9.0,270498,4520.645328,2,natural_movie_one,4520.678678
13810,0.03337,270501,9004.0,NaN,NaN,False,<NA>,897.0,<NA>,9.0,270500,4520.678678,2,natural_movie_one,4520.712048
13811,0.03336,270503,9005.0,NaN,NaN,False,<NA>,898.0,<NA>,9.0,270502,4520.712048,2,natural_movie_one,4520.745408
13812,0.03332,270505,9006.0,NaN,NaN,False,<NA>,899.0,<NA>,9.0,270504,4520.745408,2,natural_movie_one,4520.778728

In [10]:
ophys_experiment.metadata

{'equipment_name': 'CAM2P.4',
 'sex': 'F',
 'age_in_days': 161,
 'stimulus_frame_rate': 60.0,
 'session_type': 'OPHYS_5_images_B_passive',
 'date_of_acquisition': datetime.datetime(2018, 12, 14, 8, 35, 41, 725000, tzinfo=tzutc()),
 'reporter_line': 'Ai93(TITL-GCaMP6f)',
 'cre_line': 'Slc17a7-IRES2-Cre',
 'behavior_session_uuid': UUID('053e0bb4-cd11-4757-af90-43b6ce821894'),
 'driver_line': ['Camk2a-tTA', 'Slc17a7-IRES2-Cre'],
 'mouse_id': 412366,
 'project_code': 'Not Available',
 'full_genotype': 'Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-GCaMP6f)/wt',
 'behavior_session_id': 795431009,
 'indicator': 'GCaMP6f',
 'emission_lambda': 520.0,
 'excitation_lambda': 910.0,
 'ophys_container_id': 814796612,
 'field_of_view_height': 512,
 'field_of_view_width': 451,
 'imaging_depth': 375,
 'targeted_imaging_depth': 375,
 'imaging_plane_group': None,
 'imaging_plane_group_count': 0,
 'ophys_experiment_id': 795952471,
 'ophys_frame_rate': 31.0,
 'ophys_session_id': 795217244,
 'targeted_structure': 'VISp'}

Other Tables
============

In [11]:
ophys_sessions = pd.read_csv(base_path / 'ophys_session_table.csv')
ophys_sessions

,ophys_session_id,equipment_name,full_genotype,mouse_id,reporter_line,driver_line,sex,age_in_days,session_type,cre_line,...,session_number,prior_exposures_to_session_type,prior_exposures_to_image_set,prior_exposures_to_omissions,behavior_session_id,imaging_plane_group_count,ophys_experiment_id,ophys_container_id,date_of_acquisition,project_code
0,951410079,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,206.0,OPHYS_1_images_A,Sst-IRES-Cre,...,1.0,0,65.0,0,951520319,4.0,"[951980471, 951980473, 951980475, 951980479, 9...","[1018028339, 1018028342, 1018028345, 101802835...",2019-09-20 09:59:38.837,VisualBehaviorMultiscope
1,952430817,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,209.0,OPHYS_2_images_A_passive,Sst-IRES-Cre,...,2.0,0,66.0,1,952554548,3.0,"[953659743, 953659745, 953659749, 953659752]","[1018028339, 1018028345, 1018028354, 1018028357]",2019-09-23 08:45:38.490,VisualBehaviorMultiscope
2,954954402,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,210.0,OPHYS_3_images_A,Sst-IRES-Cre,...,3.0,0,67.0,2,953982960,4.0,"[958527464, 958527471, 958527474, 958527479, 9...","[1018028339, 1018028342, 1018028345, 101802835...",2019-09-24 09:01:31.582,VisualBehaviorMultiscope
3,955775716,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,212.0,OPHYS_3_images_A,Sst-IRES-Cre,...,3.0,1,68.0,3,956010809,2.0,"[956941841, 956941844, 956941846]","[1018028339, 1018028342, 1018028345]",2019-09-26 09:22:21.772,VisualBehaviorMultiscope
4,957020350,MESO.1,Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,457841,Ai148(TIT2L-GC6f-ICL-tTA2),['Sst-IRES-Cre'],F,213.0,OPHYS_4_images_B,Sst-IRES-Cre,...,4.0,0,0.0,4,957032492,4.0,"[957759562, 957759564, 957759566, 957759570, 9...","[1018028339, 1018028342, 1018028345, 101802835...",2019-09-27 08:58:37.005,VisualBehaviorMultiscope
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,993512923,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,128.0,OPHYS_2_images_B_passive,Vip-IRES-Cre,...,2.0,0,12.0,2,993537991,NaN,[993590480],[991913246],2019-12-10 12:25:49.549,VisualBehaviorTask1B
700,993668836,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,129.0,OPHYS_4_images_A,Vip-IRES-Cre,...,4.0,0,0.0,3,993691759,NaN,[993862120],[991913246],2019-12-11 08:57:44.877,VisualBehaviorTask1B
701,993948045,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,130.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,5.0,0,1.0,4,993959724,NaN,[994053909],[991913246],2019-12-12 09:29:20.785,VisualBehaviorTask1B
702,994689422,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,134.0,OPHYS_6_images_A,Vip-IRES-Cre,...,6.0,0,2.0,5,994710581,NaN,[994791582],[991913246],2019-12-16 09:27:10.443,VisualBehaviorTask1B
703,994868382,CAM2P.4,Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt,489066,Ai148(TIT2L-GC6f-ICL-tTA2),['Vip-IRES-Cre'],F,135.0,OPHYS_5_images_A_passive,Vip-IRES-Cre,...,5.0,1,3.0,6,994882261,NaN,[994956406],[991913246],2019-12-17 09:39:25.881,VisualBehaviorTask1B

In [12]:
cells_table = pd.read_csv(base_path / 'ophys_cells_table.csv')
cells_table

,cell_roi_id,cell_specimen_id,ophys_experiment_id,x,y,height,width
0,1080884343,1086496928,775614751,63,380,19,17
1,1080884173,1086496914,775614751,272,463,15,19
2,1080883843,1086496838,775614751,210,361,17,17
3,1080886674,1086491756,775614751,136,230,17,15
4,1080885658,1086491699,775614751,45,435,20,14
...,...,...,...,...,...,...,...
133130,1115385589,1120127229,1110928073,166,212,19,19
133131,1115385513,1120127083,1110928073,117,68,19,17
133132,1115301580,1120126794,1110928075,419,417,15,17
133133,1115301595,1120126500,1110928075,121,342,17,15
133134,1115301537,1120126373,1110928075,236,187,17,20